#This is a config file for the simulation chain
#Written by: Michael C. Kunkel / m.kunkel@fz-juelich.de
---
userName:
    mkunkel
topDir: 
    /work/clas12/mkunkel/CLAS12DeepLearning
clas12Dir: 
    /work/clas12/mkunkel/CLAS12DeepLearning/Reconstructed
torusValue:
#    - -0.75
#    - -1.0
    - 1.0 
StartIndex:
    1  
NinitialJobs:
    100  
NeventsPerJob:
    10000             
solenoidValue:
    - 0.8
fileName:
    - AntiNeutron
    - AntiProton
    - Electron
    - Gamma
    - KMinus
    - KPlus
    - Neutron
    - PiMinus
    - PiPlus
    - Positron
    - Proton   
claraConfig:
    /work/clas12/mkunkel/myClara5a.0.7    
gemcConfig:
    4a.2.2 
gcardLundPrefix:
    fullEtaPrimeDilepton     
path:
    /volatile/clas12/mkunkel
projectName:
     DeepLearning       
directories:
    - PID/GEMCFiles
    - PID/DecodedFiles
    - PID/ReconstructedFiles   
lundDirectory:
    PID/LundFiles  
lundPrefix:
    AllDalitz       
